#!/usr/bin/env node
/**
 * Pin the YC RFS extractor's current output as a regression baseline.
 *
 *   node scripts/pin-yc-rfs.mjs          # print what the parser extracts
 *   node scripts/pin-yc-rfs.mjs --write  # write test/golden/yc-rfs-expected.json
 *
 * ## What this can and cannot establish
 *
 * The baseline is generated by running the parser over the recorded fixture,
 * so it CANNOT tell you the parser is right — a wrong extractor pins its own
 * wrong output and the test then passes forever. That is why `--write` prints
 * every title and asks you to compare them against the live page before
 * committing. The human check is the part that establishes correctness.
 *
 * What the baseline DOES establish, once reviewed, is that the extractor has
 * not silently drifted. A change that starts returning navigation text, or
 * half the requests, or a plausible-looking list from the wrong section of the
 * page, will fail loudly instead of passing with different content — which is
 * the failure mode a parser over unversioned HTML actually has.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fixture = path.join(repoRoot, 'test', 'fixtures', 'yc-rfs.html');
const meta = path.join(repoRoot, 'test', 'fixtures', 'yc-rfs.meta.json');
const expected = path.join(repoRoot, 'test', 'golden', 'yc-rfs-expected.json');

if (!fs.existsSync(fixture)) {
  console.error(`No recorded fixture at ${path.relative(repoRoot, fixture)}.`);
  console.error('Record it first:  npm run record-fixtures -- --only=yc-rfs');
  process.exit(1);
}

const { parseRfsPage } = await import(path.join(repoRoot, 'dist', 'sources', 'ycombinator.js'));
const html = fs.readFileSync(fixture, 'utf8');
const result = parseRfsPage(html);

if (result.error !== undefined) {
  console.error(`The parser failed on the recorded page: ${result.error}`);
  console.error('Fix the extractor before pinning anything.');
  process.exit(1);
}

console.log(`Extracted ${result.requests.length} request(s)${result.batch === undefined ? '' : ` — batch: ${result.batch}`}\n`);
for (const [index, request] of result.requests.entries()) {
  console.log(`${String(index + 1).padStart(2)}. ${request.title}`);
}

if (!process.argv.includes('--write')) {
  console.log('\nRe-run with --write to pin these as the regression baseline.');
  process.exit(0);
}

const recordedAt = fs.existsSync(meta)
  ? (JSON.parse(fs.readFileSync(meta, 'utf8')).recorded_at ?? null)
  : null;

const baseline = {
  note:
    'Regression baseline for the YC RFS extractor, generated by scripts/pin-yc-rfs.mjs from the recorded ' +
    'fixture and then REVIEWED BY HAND against the live page. Generated-then-reviewed, not generated-and-trusted: ' +
    'the parser cannot validate itself, so the review is what makes this meaningful. It catches drift — an ' +
    'extractor that starts returning navigation text or a plausible list from the wrong section fails loudly ' +
    'instead of passing with different content.',
  fixture: 'yc-rfs.html',
  recorded_at: recordedAt,
  reviewed: false,
  request_count: result.requests.length,
  ...(result.batch === undefined ? {} : { batch: result.batch }),
  titles: result.requests.map((r) => r.title),
};

fs.mkdirSync(path.dirname(expected), { recursive: true });
fs.writeFileSync(expected, `${JSON.stringify(baseline, null, 2)}\n`);

console.log(`\nWrote ${path.relative(repoRoot, expected)}`);
console.log('\nNOW READ THE TITLES ABOVE against https://www.ycombinator.com/rfs.');
console.log('If they match, set "reviewed": true in that file and commit it.');
console.log('The test refuses to accept an unreviewed baseline.');
